inherit_gem:
  hint-rubocop_style:
    - default.yml

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - '**/*.haml'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*'

Metrics/ClassLength:
  Max: 150
