version: "3.7"

x-ruby: &ruby-base
  build:
    context: ./docker/ruby
    args:
      - RUBY_VERSION=2.6.5
      - NODE_VERSION=11
      - INSTALL_PG_CLIENT=true
      - UID=${UID}
      - GID=${GID}
  volumes:
    - .:/app
    - gems:/gems
    - node_modules:/app/node_modules
    - packs:/app/public/packs
    - rails_cache:/app/tmp/cache
  tmpfs:
    - /tmp
  user: ruby
  tty: true
  stdin_open: true
  depends_on:
    - postgres
    - redis

services:
  rails:
    <<: *ruby-base
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
      - "1080:1080"
      - "43447:43447"
    entrypoint: /app/docker/rails-entrypoint
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL}
      - SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD}
      - SELENIUM_REMOTE_HOST=selenium
      - BOOTSNAP_CACHE_DIR=/gems/bootsnap
  webpacker:
    <<: *ruby-base
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    entrypoint: /app/docker/webpack-entrypoint
  sidekiq:
    <<: *ruby-base
    command: bundle exec sidekiq
    entrypoint: /app/docker/sidekiq-entrypoint
    environment:
      - BOOTSNAP_CACHE_DIR=/gems/bootsnap
  selenium:
    image: selenium/standalone-chrome
  postgres:
    image: postgres:11.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    build:
      context: ./docker/redis
      args:
        - REDIS_VERSION=4.0
    volumes:
      - redis:/data

volumes:
  postgres-data:
  gems:
  redis:
  node_modules:
  packs:
  rails_cache:
